name: Changelog & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm ci || npm install
      - name: Run standard-version
        run: |
          npx standard-version --skip.tag --skip.commit
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install github_changelog_generator
        run: gem install github_changelog_generator
      - name: Run github_changelog_generator
        run: github_changelog_generator -u youruser -p mastopi
      - name: Commit and push changelogs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add CHANGELOG.md RELEASE_NOTES.md || true
          git commit -m 'docs: update changelog [ci skip]' || echo 'No changes'
          git push
